### ISSUE TITLE
Store password encrypted!

### ISSUE THREAD

**Issue by Apollon77** [MeisterTR/ioBroker.proxmox#6]
Passwords are currently stored unencrypted ... you should change that!

Example: Alexa2. I can give support if needed

**Comment by MeisterTR** [comment]
done

**Comment by Apollon77** [comment]
Thank you!

**Comment by Apollon77** [comment]
I do not think that this is enough ... It could be that the dta-crypt tag works in admin (never seen it before) :-) but the adapter needs to decrypt the passwort in any case before usage!

**Comment by Apollon77** [comment]
Also in Admin this is not enough! Additional logic is missing

**Comment by MeisterTR** [comment]
ahh ok i see. i thought the encryption was done by the js-controller.  should i use the same secret key from alexa2? or something else?

socket.emit('getObject', 'system.config', function (err, obj) {
                secret = (obj.native ? obj.native.secret : '') || '#########';
                loadHelper(settings, onChange);

can i config a secretkey in admin? or where are the data (system.config) from?

**Comment by Apollon77** [comment]
The hard coded static key is only for vereerryy old ioBroker installations as fallback do yes use that one. Secret is generated on initial install of ioBroker  normally and then stored there. So not editable and this is ok so ;-)

**Comment by Apollon77** [comment]
So you need additional functions and code in admin html (to encrypt and decrypt and such and you need the decrypt method in your main.js

**Comment by Apollon77** [comment]
Did a short check/review (hope ok):
* admin never decrypts the password ...so changing something without resetting pws will double encrypt it ... you should decrypt on load :-)
* https://github.com/MeisterTR/ioBroker.proxmox/blob/master/lib/proxmox.js#L19 ?! :-)

**Comment by MeisterTR** [comment]
can i just copy these lines?
https://github.com/Apollon77/ioBroker.alexa2/blob/master/admin/index_m.html#L94 into my admin?
